In [19]:
import numpy as np
import time

In [21]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5,"prime"])

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [23]:
print(arr2D,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [49]:
arr1 = np.zeros((2,3), dtype = "int32") #prefill with zero
print(arr1,arr1.shape)

arr2 = np.ones((2,3), dtype = "int32") #prefill
print(arr2,arr2.shape)

arr3 = np.full((3,4), 100) #prefill with value
print(arr3,arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4,arr4.shape)

#range(start, end, step)
arr5 = np.arange(1,10,2) #range element
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,3) #evenly space arrays
print(arr6,arr6.shape) #shape print the dimention 

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [55]:
#property
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D.shape) #shape of array (3,3,)
print(arr2D.size) #size  of array = 9
print(arr2D.dtype) #data type
print(arr2D.ndim) # n dimension 

arr2DFloat = arr2D.astype(np.float64)
print(arr2DFloat, arr2DFloat.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [59]:
#Operation on array 

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshared = arr.reshape((3,2))
print(reshared, reshared.shape)

flattened = arr.flatten() #convert 2D to 1D 
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [66]:
#indexing

arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])

#2D indexing access
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D[0][1])
print(arr2D[1][0])

#fancy Indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,3]
print(arr[idx])

#boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr > 3])
print(arr[arr % 2 ==0])

1
2
2
4
[1 2 4]
[4 5]
[2 4]


In [72]:
#Slicing
#[start, end, step]
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])



[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [75]:
#py List vs NumPy array
#copy vs view 
#py list make copy and update copy 
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

#NumPy Array make a view and change on originial Array only.
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

#NumPy how to Copy, using .copy of view 


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [86]:
 #Data Type

arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)

arr = np.array([1,2,3,4,5.0])
print(arr, arr.dtype)

arr = np.array([1,2,3,4,5.0])
print(arr, arr.dtype)


[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
