In [1]:
import numpy as np
import time

In [2]:
size = 10_000_000

#python list
py_list = list(range(size))

start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()

print(f"python list time = {end - start} seconds")

#numPy list
np_arr = np.array(py_list)

start = time.time()
#vectorization
sq_list = np_arr ** 2
end = time.time()


print(f"NumPy list time = {end - start} seconds")

python list time = 1.646113395690918 seconds
NumPy list time = 0.2655305862426758 seconds


In [3]:
import sys

print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"NumPy array size = {np_arr.nbytes} bytes")

Python list size = 800000560000000 bytes
NumPy array size = 80000000 bytes


In [12]:
#3darray example multidimensional array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2D)

print(np.sum(arr2D)) # sum of all

sum_of_column = np.sum(arr2D, axis = 0) # sum of column 
print(sum_of_column )

sum_of_row = np.sum(arr2D, axis = 1) #sum of row 
print(sum_of_row )

print(arr2D[0:2,1]) #extract partial array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[2 5]


In [22]:
#3darray example multidimensional array

arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2x3x2 matrix or 3D array

print(arr , arr.shape)
print(arr[0,1,1])
print(arr[1,1,0])

#slicing 

print(arr[:,0,0:]) #first row of both matrix
print(arr[:,:,0]) #first column of both matrix

arr[:,:,0] = 99 #update same value to all selected attribute in array

print(arr[:,:,0])
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[99 99 99]
 [99 99 99]]
[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99 10]
  [99 12]]]


In [24]:
#vectorizaiton 

arr = np.array([1,2,3,4,5])

print(arr **2)
print(arr + 2)

[ 1  4  9 16 25]
[3 4 5 6 7]


In [28]:
#boardcasting

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])


print(arr + arr2)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [33]:
#vencor normalization
#std normalization  
# (arr - mean)

arr = np.array([[1,2],[3,4],[5,6]])

mean = np.mean(arr)
std = np.std(arr)
print(np.mean(arr))
print(np.std(arr))

normalized_arr = (arr - mean)/std 

print(normalized_arr)


3.5
1.707825127659933
[[-1.46385011 -0.87831007]
 [-0.29277002  0.29277002]
 [ 0.87831007  1.46385011]]


In [46]:
#function 

#aggregation 

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))

#power function
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

15
120
3.0
5
0
4
1.4142135623730951
3.0
3.0
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [49]:
#log
arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
#rounding

arr = np.array([1,2,3,4,5])


